LaravelAlma/MiLaravel/routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use App\Models\Publicacio;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

$userController = \App\Http\Controllers\UserController::class;

Route::get('/', [$userController, 'index'])->name('index');

Route::get('/profile/adds', [$userController, 'showAdds'])->name('showAdds');

Route::get('/profile/saved', [$userController, 'showSaved'])->name('showSaved');

Route::get('/profile/newAdd', [$userController, 'showNewAddForm'])->name('showNewAddForm');

Route::get('/selectedAdd/{idPublicacio}', [$userController, 'selectedAdd'])->name('selectedAdd');

Route::get('/add/{idPublicacio}/newComment/{text}', [$userController, 'newCommentNotRequest'])->name('newCommentNotRequest');

Route::post('/storeNewAdd', [$userController, 'storeNewAdd'])->name('storeNewAdd');

Route::post('/guardar-favorito', [$userController, 'guardar'])->name('guardarFavorito');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

LaravelAlma/MiLaravel/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

LaravelAlma/MiLaravel/resources/views/adds.blade.php
<div>
    <!-- Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi -->
</div>

LaravelAlma/MiLaravel/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    {{ __("You're logged in!") }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

LaravelAlma/MiLaravel/resources/views/index.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publicaciones</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

<div class="max-w-4xl mx-auto px-4 py-8">
    @foreach($publicacions as $publicacio)
        <a href="{{ route('selectedAdd', $publicacio->id) }}" class="block mb-4 hover:bg-gray-50 rounded-lg shadow-md px-6 py-4 flex justify-between items-center">
            <p class="text-lg font-semibold text-gray-800">{{ $publicacio->titol }}</p>
            <form method="POST" action="{{ route('guardarFavorito') }}" class="inline-block">
                @csrf
                <input type="hidden" name="publicacio_id" value="{{ $publicacio->id }}">
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md">Guardar como favorito</button>
            </form>
        </a>
    @endforeach
</div>

</body>
</html>

LaravelAlma/MiLaravel/resources/views/newAdd.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear nueva publicacion</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

<div class="max-w-md mx-auto mt-10 px-4 py-8 bg-white shadow-md rounded-lg">
    <h1 class="text-2xl font-bold mb-6">Formulario para crear una nueva oferta de coche</h1>

    <form action="{{ route('storeNewAdd') }}" method="POST">
        @csrf
        <div class="mb-4">
            <label for="titulo" class="block text-sm font-medium text-gray-700">Título:</label>
            <input type="text" id="titulo" name="titulo" class="mt-1 p-2 block w-full border rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
        </div>
        <div class="mb-4">
            <label for="descripcion" class="block text-sm font-medium text-gray-700">Descripción:</label>
            <input type="text" id="descripcion" name="descripcion" class="mt-1 p-2 block w-full border rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
        </div>
        <div class="mb-4">
            <label for="marca" class="block text-sm font-medium text-gray-700">Marca:</label>
            <input type="text" id="marca" name="marca" class="mt-1 p-2 block w-full border rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
        </div>
        <div class="mb-4">
            <label for="modelo" class="block text-sm font-medium text-gray-700">Modelo:</label>
            <input type="text" id="modelo" name="modelo" class="mt-1 p-2 block w-full border rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
        </div>
        <div class="mb-4">
            <label for="ano" class="block text-sm font-medium text-gray-700">Año:</label>
            <input type="number" id="ano" name="ano" class="mt-1 p-2 block w-full border rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
        </div>
        <div class="mb-4">
            <label for="precio" class="block text-sm font-medium text-gray-700">Precio:</label>
            <input type="number" id="precio" name="precio" class="mt-1 p-2 block w-full border rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
        </div>
        <div class="mb-6">
            <label for="kilometros" class="block text-sm font-medium text-gray-700">Kilometros:</label>
            <input type="number" id="kilometros" name="kilometros" class="mt-1 p-2 block w-full border rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
        </div>
        <button type="submit" class="w-full px-4 py-2 bg-blue-500 text-white rounded-md shadow-md hover:bg-blue-600">Crear Oferta</button>
    </form>
</div>

</body>
</html>

LaravelAlma/MiLaravel/resources/views/saved.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ofertas Guardadas</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

<div class="max-w-4xl mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-6">Ofertas Guardadas por {{ $user->name }}</h1>

    <ul class="list-disc pl-4">
        @foreach($ofertasGuardadas as $oferta)
            <li class="text-lg text-gray-800 mb-2">{{ $oferta->marca }} - {{ $oferta->modelo }}</li>
            <!-- Ajusta las propiedades según la estructura de tu modelo Publicacio -->
        @endforeach
    </ul>
</div>

</body>
</html>

LaravelAlma/MiLaravel/resources/views/selectedAdd.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles de la Oferta</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

<div class="max-w-4xl mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-6">Detalles de la Oferta</h1>

    <div class="bg-white shadow-md rounded-lg p-8">
        <h2 class="text-xl font-bold mb-4">{{ $publicacio->titol }}</h2>
        <p class="text-gray-600 mb-6">{{ $publicacio->descripcio }}</p>

        <!-- Información del coche -->
        <div class="grid grid-cols-2 gap-4">
            <div>
                <p class="text-lg font-semibold mb-2">Cotxe</p>
                <p><span class="font-semibold">Marca:</span> {{ $cotxe->marca }}</p>
                <p><span class="font-semibold">Model:</span> {{ $cotxe->model }}</p>
                <p><span class="font-semibold">Any:</span> {{ $cotxe->any }}</p>
            </div>
            <div>
                <p><span class="font-semibold">Preu:</span> {{ $cotxe->preu }}</p>
                <p><span class="font-semibold">Kilometres:</span> {{ $cotxe->kilometres }}</p>
            </div>
        </div>

        <!-- Comentarios -->
        <div class="mt-8">
            <h2 class="text-lg font-semibold mb-4">Comentaris</h2>
            <ul>
                @foreach($publicacio->comentaris as $comentari)
                    <li class="border-b border-gray-200 py-4">
                        <p class="text-lg font-semibold mb-2">{{ $comentari->usuari ? $comentari->usuari->name : 'Usuario desconocido' }}</p>
                        <p class="text-gray-600">{{ $comentari->text }}</p>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>

</div>

</body>
</html>

LaravelAlma/MiLaravel/resources/views/showAdds.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publicaciones de {{ $user->name }}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

<div class="max-w-4xl mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-6">Publicaciones de {{ $user->name }}</h1>

    <ul class="list-disc pl-4">
        @foreach($publicaciones as $publicacion)
            <li class="text-lg text-gray-800 mb-2">{{ $publicacion->titol }} - {{ $publicacion->descripcio }}</li>
            <!-- Ajusta las propiedades según la estructura de tu modelo Publicacio -->
        @endforeach
    </ul>
</div>

</body>
</html>

LaravelAlma/MiLaravel/resources/views/showSaved.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publicaciones favoritas de {{ $user->name }}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

<div class="max-w-4xl mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-6">Publicaciones favoritas de {{ $user->name }}</h1>

    <ul class="list-disc pl-4">
        @foreach($ofertasGuardadas as $publicacion)
            <li class="text-lg text-gray-800 mb-2">{{ $publicacion->titol }} - {{ $publicacion->descripcio }}</li>
            <!-- Ajusta las propiedades según la estructura de tu modelo Publicacio -->
        @endforeach
    </ul>
</div>

</body>
</html>